[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Ambiance-Flat-Red
Comment=Ambiance-Flat, a redesigned modern & flat theme with modern colors. Originally by RAVEfinity.com, now maintained by Elbullazul
Encoding=UTF-8

Name[en_CA]=index-aqua.theme

[X-GNOME-Metatheme]
GtkTheme=Ambiance-Flat-Aqua
MetacityTheme=Ambiance-Flat-Aqua
IconTheme=Vibrancy-Full-Dark-Aqua
CursorTheme=DMZ-White
ButtonLayout=close,minimize,maximize:
