[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Ambiance-Flat-Graphite
Comment=Ambiance Flat, A Redesigned Modern & Flat, Ambiance Based Theme W/New Colors By RAVEfinity.com
Encoding=UTF-8

Name[en_CA]=index-graphite.theme

[X-GNOME-Metatheme]
GtkTheme=Ambiance-Flat-Graphite
MetacityTheme=Ambiance-Flat-Graphite
IconTheme=Vibrancy-Full-Dark-Graphite
CursorTheme=DMZ-White
ButtonLayout=close,minimize,maximize:
